# Copyright 2026 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "backend.conf"

# This is the main configuration file for the application.
# ~~~~~

appName = rds-cande-proxy

# Default http client
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.AuthModule"

# Play Modules
play.modules.enabled += "uk.gov.hmrc.rdscandeproxy.Module"

# The application languages
# ~~~~~
play.i18n.langs = ["en"]

# Router
# ~~~~~
# Define the Router object to use for this application.
# This router will be looked up first when the application is starting up,
# so make sure this is the entry point.
# Furthermore, it's assumed your route file is named properly.
# So for an application router like `my.application.Router`,
# you may need to define a router file `conf/my.application.routes`.
# Default to Routes in the root package (and conf/routes)
# !!!WARNING!!! DO NOT CHANGE THIS ROUTER
play.http.router = prod.Routes

# Controller
# ~~~~~
# By default all controllers will have authorisation, logging and
# auditing (transaction monitoring) enabled.
# The below controllers are the default exceptions to this rule.


# Microservice specific config
microservice {
  services {
    auth {
      host = localhost
      port = 8500
    }
  }
}

# override these in app-config-<env>, not db.default.xyz
oracle.euvat {
  db.host = "localhost"
  db.port = 1521
  dbName = "xe"
  username = "euvat_data"
  password = "euvat_data"
  connectionTimeout = 50s
  validationTimeout = 5s
  idleTimeout = 10m
  maximumPoolSize = 10
  protocol = TCP
  sslServerCertDn = "N/A"
  connectionType = SID
  encodedCertDN = false
}

# EUVAT DB config
db {
  default {
    url = """jdbc:oracle:thin:@
        ( DESCRIPTION=
          ( ADDRESS_LIST=
            (FAILOVER=ON)
            (LOAD_BALANCE=ON)
            ( ADDRESS=
              (PROTOCOL="""${oracle.euvat.protocol}""")
              (HOST="""${oracle.euvat.db.host}""")
              (PORT="""${oracle.euvat.db.port}""")
            )
          )
          (CONNECT_DATA=
            (SERVER=DEDICATED)
            ("""${oracle.euvat.connectionType}"""="""${oracle.euvat.dbName}""")
          )
          (SECURITY=
            (SSL_SERVER_CERT_DN="""${oracle.euvat.sslServerCertDn}""")
          )
        )"""
    driver = "oracle.jdbc.OracleDriver"
    username = ${oracle.euvat.username}
    password = ${oracle.euvat.password}
    hikaricp {
      connectionTimeout = ${oracle.euvat.connectionTimeout}
      validationTimeout = ${oracle.euvat.validationTimeout}
      minimumIdle = 1
      maximumPoolSize = ${oracle.euvat.maximumPoolSize}
      idleTimeout = ${oracle.euvat.idleTimeout}
      maxLifetime = 1h
      poolName = "filingDB"
      connectionInitSql = "ALTER SESSION SET NLS_TERRITORY = 'UNITED KINGDOM'"
    }
  }
}
